### ISSUE TITLE
New Input system issue with v3.1.0

### ISSUE THREAD

**Issue by TauseefAhmaad** [mapbox/mapbox-unity-sdk#1990]
please update the SDK , i am facing these issue in the unity 6.3

**Issues in the latest SDK** 

/Users/smttech/Downloads/mapbox-unity-sdk-main/Runtime/Mapbox/Example/Scripts/PointerInput.cs(5,35): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?) /Users/smttech/Downloads/mapbox-unity-sdk-main/Runtime/Mapbox/Example/Scripts/PointerInput.cs(4,30): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?) /Users/smttech/Downloads/mapbox-unity-sdk-main/Runtime/Mapbox/Example/Scripts/PointerInput.cs(3,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

**Comment by RRebelDev** [comment]
Hi, 

with sdk 3.1.0 I'm facing the same issues on Unity 6.4. I created a new Project (Universal 3D) and followed the steps to install the package. Setup dialog does not appear and same error as TauseefAhmaad described occur.

**Comment by brnkhy** [comment]
@TauseefAhmaad @RRebelDev looks like a basic error, Examples assembly doesn't have a reference to the Input library 🤦‍♂️ 
If you select the assembly and add the reference, it should work
<img width="1465" height="817" alt="Image" src="https://github.com/user-attachments/assets/4a4e9ced-7219-4151-bc54-152f328292b7" />

then you need to do this in demo scenes as well by the way
<img width="866" height="302" alt="Image" src="https://github.com/user-attachments/assets/224c9f5a-4397-4176-bc70-4ecf2ea73b5d" />

First fix is easy but I guess I should find an easier way for that second part as well 🤔

**Comment by brnkhy** [comment]
Turns out this is an annoyingly complicated problem to fix. As described above, if you check that box, it should work for you no problem; but for me to create the package such that demo scenes will work with  all combinations of `2022.3 x unity6 x old input x new input`, I'll have to create separate assemblies for the demo/example scripts and do all sorts of trickery etc.... frustrating.

**Comment by RRebelDev** [comment]
Hi @brnkhy 
thanks for the investigation. Seems like you are right, as soon as is I followed the steps you described, I could import the example scene and play around with it. It still feels a bit hacky not to have an "official" MapBox SDK for Unity and to use those kind of workarounds, but I think for now thats working.

**Comment by brnkhy** [comment]
@RRebelDev you are absolutely right, it's just a little frustrating having to create separate assemblies and abstractions for such a small thing. Unity is like that sometimes :( but fix will be in soon

**Comment by brnkhy** [comment]
here's the minimal fix; https://github.com/mapbox/mapbox-unity-sdk/tree/fix/input-system-package-dep
it's a small change, it took time because I initially didn't want to do this and tried to fix it using multiple assemblies just not to add new input package as dependency  but I feel like not adding ugly complexity is better in this case. It should work with existing projects without any issues as well but needs testing/feedback of course.

**Comment by brnkhy** [comment]
Unfortunately I couldn't merge this in time, I'll be on vacation until the end of the month and I'll have to delay merging this until then :(

**Comment by TauseefAhmaad** [comment]
The project runs successfully in Unity Editor (Unity 6.3.x LTS) however, building for the Android platform results in multiple Android-specific errors.
Issue 1: Duplicate class found (AndroidX vs. Old Support Libraries)

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :launcher
WARNING: The option setting 'android.jetifier.ignorelist=support-v4-25.1.0' is experimental.

> Configure project :unityLibrary
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Configure project :launcher
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :launcher:mergeReleaseNativeDebugMetadata NO-SOURCE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:writeReleaseAarMetadata UP-TO-DATE
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseJavaWithJavac NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibRuntimeToDirRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:writeReleaseAarMetadata UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:prepareReleaseArtProfile UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:createFullJarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractProguardFiles UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseLintModel UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractDeepLinksForAarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractReleaseAnnotations UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseJavaResource UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:syncReleaseLibJars UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleReleaseLocalLintAar UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:writeReleaseLintModelMetadata UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:lintVitalAnalyzeRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseLintVitalModel UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:copyReleaseJniLibsProjectOnly UP-TO-DATE

> Task :launcher:checkReleaseDuplicateClasses
WARNING: [CoreRemapperImpl] No mapping for: android/support/coreutils/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/coreutils/BuildConfig
WARNING: [PathRewrite] No mapping for: android/support/coreutils/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/mediacompat/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/mediacompat/BuildConfig
WARNING: [PathRewrite] No mapping for: android/support/mediacompat/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/coreui/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/coreui/BuildConfig
WARNING: [PathRewrite] No mapping for: android/support/coreui/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/compat/BuildConfig
WARNING: [CoreRemapperImpl] No mapping for: android/support/compat/BuildConfig
WARNING: [PathRewrite] No mapping for: android/support/compat/BuildConfig

> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses FAILED
> Task :launcher:checkReleaseAarMetadata UP-TO-DATE

> Task :unityLibrary:compileReleaseJavaWithJavac FAILED

[Incubating] Problems report is available at: file:///Users/smttech/Desktop/TestProjects/Metamorphosis360-Unity/Library/Bee/Android/Prj/IL2CPP/Gradle/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.13/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
46 actionable tasks: 2 executed, 44 up-to-date

UnityEditor.EditorApplication:Internal_CallDelayFunctions () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:407)


## Issue 2: `error: cannot find symbol ViewCompat.getRootWindowInsets`

**Comment by brnkhy** [comment]
Hey @TauseefAhmaad,
do you think these are input system related at all? or did you remember to use gradle settings, described in readme file?
