### ISSUE TITLE
Mapbox menu does not appear on import

### ISSUE THREAD

**Issue by heaversm** [mapbox/mapbox-unity-sdk#233]
I'm using Unity 2017b10 - which is necessary for running ARKit in Unity. If you attempt to import the Mapbox package, it says that it uses obsolete APIs, and after converting them and finishing the import, the Mapbox menu does not appear. Any fix for this? Any way to still use the mapbox asset without it?

**Comment by david-rhodes** [comment]
@heaversm My guess is that you still have compile errors and so our scripts have not actually compiled (and therefore, no window). We're using 2017 internally, so I can confirm our SDK is compatible. Please just check your console for exceptions (and log them here if you can't fix them).

**Comment by heaversm** [comment]
well - I'm just creating a blank project and importing the asset. The error I get if I import and play the `MeshGenerationOnTerrain` is:

<img width="1009" alt="screen shot 2017-09-08 at 1 52 55 pm" src="https://user-images.githubusercontent.com/520541/30230892-1f7a25bc-949d-11e7-96ec-9643875dbe9a.png">

**Comment by david-rhodes** [comment]
So it seems the 2017 API automatic upgrade failed in your case. Please just change the code referenced there to `Application.identifier`.

**Comment by heaversm** [comment]
Did that, but still no menu

**Comment by david-rhodes** [comment]
Restart Unity? Reimport Mapbox folder (from right-click menu)?

**Comment by heaversm** [comment]
Tried that - noticed this on upgrading scripts this time around:

```
error CS0006: Metadata file `/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Timeline/RuntimeEditor/UnityEngine.Timeline.dll' could not be found
error CS0006: Metadata file `/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UIAutomation/UnityEngine.UIAutomation.dll' could not be found
error CS0006: Metadata file `/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnityGoogleAudioSpatializer/RuntimeEditor/UnityEngine.GoogleAudioSpatializer.dll' could not be found
error CS0006: Metadata file `/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/UnitySpatialTracking/RuntimeEditor/UnityEngine.SpatialTracking.dll' could not be found
error CS0006: Metadata file `/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll' could not be found
error CS0006: Metadata file `/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll' could not be found
```

**Comment by david-rhodes** [comment]
Sounds like you have a bad unity install or something. I don't think this is Mapbox-specific.

**Comment by heaversm** [comment]
Possibly - but I'm using the most recent public link to the Unity beta (https://unity3d.com/unity/beta) - v2017.2.0b10 - so I may not be the only one who has issues using the plugin

**Comment by heaversm** [comment]
Confirmed that this works with standard version of Unity 5.6.2f1 though. Just need to make sure I have a version that works with ARKit

**Comment by david-rhodes** [comment]
I really think you still have compile errors.

**Comment by heaversm** [comment]
OK - will let you know if I sort it out. Excited to work with the plugin regardless.

**Comment by david-rhodes** [comment]
@heaversm Maybe you can try 2017.1? We use this internally, and ARKit works fine with it.

**Comment by heaversm** [comment]
Yep - confirmed that it works with 2017.1.3. I'll close this for now since 2017.1.3 works with ARKit. Thanks for your help.
