### ISSUE TITLE
The type or namespace name 'ARBackgroundRenderer' could not be found

### ISSUE THREAD

**Issue by Msnkhosravi** [mapbox/mapbox-unity-sdk#1753]
Unity version 2020.2.2
trying to import Mapbox but it won't get imported with the error: The type or namespace name 'ARBackgroundRenderer' could not be found.

Is there any way to fix it?

I already tried importing ARFoundation package and ARCore Package but non are working. 

Thanks in advance

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by matt-heavy** [comment]
Also trying to resolve this. 

Tried resolving the errors by switching ARBackgroundRenderer to ARCameraBackground as some of the properies seemed similar, but not getting any camera feed when I build.

**Comment by Sailendrakc** [comment]
Any fix or workaround yet?

**Comment by soulio2005** [comment]
Any fix yet ?

**Comment by Sailendrakc** [comment]
I deleted the AR related folders and assets that comes with mapbox and it worked. I use ar foundation from unity package manager.

**Comment by abullard** [comment]
> I deleted the AR related folders and assets that comes with mapbox and it worked. I use ar foundation from unity package manager.

Confirming this comment. This error was blocking the Mapbox Setup window from opening. After removing Mapbox's AR related content, the C# scripts compiled without error and the Setup window opened.

**Note (for the purposes of having this documented somewhere)**: I installed ARKit XR Plugin v4.0.12 (for iOS support) and AR Foundation v4.0.12 to get AR support on my Unity Project. My project also used Mapbox Unity SDK v2.1.1.

Thanks for the help @Sailendrakc

**Comment by sam1am** [comment]
Running into this as well. The Mapbox SDK fails to install in the latest LTS version of Unity. Documentation needs to be updated on the install page to tell you which libraries or dependencies need to be installed. Reverting to 2019 LTS release and installing the XR Plugin Management package in the package manager got me up and running.

**Comment by vStamatakis** [comment]
@abullard Can you help as, the newbies? What exactly you don't import?

**Comment by soulio2005** [comment]
> > I deleted the AR related folders and assets that comes with mapbox and it worked. I use ar foundation from unity package manager.
> 
> Confirming this comment. This error was blocking the Mapbox Setup window from opening. After removing Mapbox's AR related content, the C# scripts compiled without error and the Setup window opened.
> 
> **Note (for the purposes of having this documented somewhere)**: I installed ARKit XR Plugin v4.0.12 (for iOS support) and AR Foundation v4.0.12 to get AR support on my Unity Project. My project also used Mapbox Unity SDK v2.1.1.
> 
> Thanks for the help @Sailendrakc



> > I deleted the AR related folders and assets that comes with mapbox and it worked. I use ar foundation from unity package manager.
> 
> Confirming this comment. This error was blocking the Mapbox Setup window from opening. After removing Mapbox's AR related content, the C# scripts compiled without error and the Setup window opened.
> 
> **Note (for the purposes of having this documented somewhere)**: I installed ARKit XR Plugin v4.0.12 (for iOS support) and AR Foundation v4.0.12 to get AR support on my Unity Project. My project also used Mapbox Unity SDK v2.1.1.
> 
> Thanks for the help @Sailendrakc

Hello there, can you tell me the exact folders you deleted? may thanks

**Comment by TaylorAbraham** [comment]
@soulio2005 I got it working by deleting GoogleARCore, MapboxAR, and UnityARInterface. This may cause issues if you want to use the AR parts of Mapbox, but I was just looking to use Mapbox for the maps so this worked for me. Hope this helps :)

**Comment by Sreee47** [comment]
This same issue persist on Unityt 2021.1.5f1. Is there any work around to use the MapboxAr feature? I have added all ARCore plugins and Arfoundation plugins. But the ARBackgroundRenderer still persists.
![image](https://user-images.githubusercontent.com/24306209/120183264-1b2a3580-c22d-11eb-9293-0661a64be9f8.png)

**Comment by flimbo** [comment]
> This same issue persist on Unityt 2021.1.5f1. Is there any work around to use the MapboxAr feature? I have added all ARCore plugins and Arfoundation plugins. But the ARBackgroundRenderer still persists.
> ![image](https://user-images.githubusercontent.com/24306209/120183264-1b2a3580-c22d-11eb-9293-0661a64be9f8.png)

I had same problem, when you check Channelog for ARFoundation you find that it was renamed.
So you need fix it your code or wait for them to fix it in new package. 

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/changelog/CHANGELOG.html
-----------------
[1.0.0-preview.9] - 2018-06-06
Rename ARBackgroundRenderer to ARCameraBackground
-----------------------

Another soludion is to downgrade  Unity to 2018 version.
then you can import package with no problem. 

it works for me at least.

**Comment by adilaghayev** [comment]
This is still broken in Unity 2020.3.18f

I don't really want to downgrade to 2018.

**Comment by mattgoulet** [comment]
Any update on this mapbox unity setup issue? It seems very consistent across multiple users.

**Comment by brnkhy** [comment]
Hey everyone,
I'm sorry to say this but there'll probably won't be an AR fix/rework any time soon. So at the moment I can only suggest deleting all AR folders in the SDK and creating your own AR solution. I'll try to keep you updated if anything changes on AR front. :(

**Comment by pmavron** [comment]
Unity 2019.2.0 should work. You may have to play around with the settings: ARM64 vs. Universal, descriptions, etc.

**Comment by chazarnik** [comment]
> Running into this as well. The Mapbox SDK fails to install in the latest LTS version of Unity. Documentation needs to be updated on the install page to tell you which libraries or dependencies need to be installed. Reverting to 2019 LTS release and installing the XR Plugin Management package in the package manager got me up and running.

Hi, this may sound stupid but would unchecking all folders that say "AR" when importing also do the trick? I am not really sure of what to delete after importing the Mapbox SDK.

**Comment by marcosvvp** [comment]
Just confirmed that the latest stable release (mapbox-unity-sdk_v2.1.1) is working on Unity 2018.4.36f1 (18 Jun, 2021).

Tested with Unity 2021.3.6f1 and 2019.4.40f1, and had no success importing the package.

For those that are just looking for a way to try out the package might be a workaround.

PS: Just landed here and have no idea how to update or change the code in order to work with newer Unity releases, which is why I tried these older ones.

**Comment by juarezjl** [comment]
Same problem here. any ideas how to make it work with the new releases of unity (ex 2022.1.11f1)?

**Comment by Haris42474** [comment]
Found the solution
just import AR foundation
After that go to all 4 file and change **ARBackgroundRenderer**  to **ARCamera**  it will work on latest versions
Map box have not updated their sdk, so the error is occuring

**Comment by davidsonclem** [comment]
Same problem here. Any idea how it will work with newer 2022.1.11f1 or 2022.1.41f1 ?

**Comment by devsleeper** [comment]
2021.3.14f

**Comment by samavan** [comment]
Quick fix on my side :
1. Be sure to enable the following packages : AR Foundation // ARCore XR Plugin
2. Rename every ARBackgroundRenderer as ARCameraBackground and add the need reference.
3. I believe you can remove every "m_BackgroundRenderer.camera = " cause that call is obselete. 
"Component.camera' is obsolete: 'Property camera has been deprecated. Use GetComponent<Camera>() instead. (UnityUpgradable)'" 
4. I guess m_BackgroundRenderer.backgroundMaterial should be m_BackgroundRenderer.customMaterial insted.
5. Commented a few more lines related to the *.mode which I didn't find a solution yet...

Here are the 4 files to replaces.
Didn't try the AR yet if still working...
At least the plugin isn't reporting error anymore.
[mapbox_2021.3.10f1-fix.unitypackage.zip](https://github.com/mapbox/mapbox-unity-sdk/files/10422571/mapbox_2021.3.10f1-fix.unitypackage.zip)

**Comment by GENOrous** [comment]
any update for this error: "error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)"
